name: rop2-api

services:
  go-server:
    build: .
    restart: unless-stopped
    ports:
      # 2231为宿主机实际暴露端口
      - "2231:8080"
    environment:
      - GIN_MODE=release
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    # mysql:8.4无法初始化
    image: "mysql:8"
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - LANG=C.UTF-8
      - TZ=Asia/Shanghai
    volumes:
      - rop2_db:/var/lib/mysql:rw
    healthcheck:
      test: "mysql -u root -p'root' -e \"SELECT VERSION();CREATE DATABASE IF NOT EXISTS rop2;\""
      start_period: 15s
      interval: 1s
      timeout: 1s
      retries: 10

volumes:
  rop2_db:
