name: rop2-api

services:
  go-server:
    build: .
    ports:
      - "2231:8080"
    environment:
      # - GIN_MODE=release
      - ROP2_Addr=0.0.0.0:8080
      - ROP2_DSN=root:root@tcp(mysql:3306)/rop2?charset=utf8mb4&loc=Local&parseTime=true
      - ROP2_LoginCallbackRegex=^https?://www.qsc.zju.edu.cn(/.*)?$
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    # mysql:8.4无法初始化
    image: "mysql:8"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - rop2_db:/var/lib/mysql:rw
    healthcheck:
      test: "mysql -u root -p'root' -e \"SELECT VERSION();CREATE DATABASE IF NOT EXISTS rop2;\""
      start_period: 15s
      interval: 3s
      timeout: 3s
      retries: 10

volumes:
  rop2_db:
